force-app/main/default/objects/CalEnergy_Settings__mdt/CalEnergy_Settings__mdt.object-meta.xml
<CustomObject>
    <label>CalEnergy Settings</label>
    <pluralLabel>CalEnergy Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CalEnergy_Settings__mdt/fields/Error_Emails__c.field-meta.xml
<CustomField>
    <fullName>Error_Emails__c</fullName>
    <label>Error Emails</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/sendErrorEmail.cls
public with sharing class sendErrorEmail {
    public sendErrorEmail() {

    }

    public static void send(Exception ex) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();


        CalEnergy_Settings__mdt ceSettings = [SELECT Error_Emails__c from CalEnergy_Settings__mdt where DeveloperName = 'Org_Settings' Limit 1];
        



        if(ceSettings.Error_Emails__c != null){
            List<String> emailAddresses = new List<String>();
            emailAddresses.addAll(ceSettings.Error_Emails__c.split(','));

            mail.setToAddresses(emailAddresses);
            mail.setSubject('Salesforce HTTP Callout Error');
            mail.setPlainTextBody('An error occurred during HTTP callout:\n\n' +
                                ex.getMessage() + '\n\n' +
                                ex.getStackTraceString());

            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
        }
    }
}