force-app/main/default/objects/CalEnergy_Settings__mdt/CalEnergy_Settings__mdt.object-meta.xml
<CustomObject>
    <label>CalEnergy Settings</label>
    <pluralLabel>CalEnergy Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CalEnergy_Settings__mdt/fields/Disable_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Disable Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CalEnergy_Settings__mdt/fields/Error_Emails__c.field-meta.xml
<CustomField>
    <fullName>Error_Emails__c</fullName>
    <label>Error Emails</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalEnergy_Settings__mdt/fields/QB_Company_Id_c__c.field-meta.xml
<CustomField>
    <fullName>QB_Company_Id_c__c</fullName>
    <label>QB Company Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/inv_AccountTriggerHandler.cls
public class inv_AccountTriggerHandler {
    

    public static Boolean disableTrigger = false;


    public static void handleAfterTrigger(List<Account> listNew, Map<Id, Account> oldMap, Boolean isInsert, Boolean isUpdate, Boolean isDelete) {

        CalEnergy_Settings__mdt ceSettings = [SELECT QB_Company_Id_c__c, Disable_Trigger__c, Error_Emails__c from CalEnergy_Settings__mdt where DeveloperName = 'Org_Settings' Limit 1];
        

        if(ceSettings.Disable_Trigger__c != TRUE){
            
            
            for(Account acc : listNew){

                if(isInsert && (acc.Quickbook_Customer_ID_c__c == '' || acc.Quickbook_Customer_ID_c__c == null)){
                    createCustomerCallout.createCustomer(acc.Id, ceSettings.QB_Company_Id_c__c);
                }
            }
        }
        
        

    }
}